name: Unit and Integration tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]

    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

#      - name: Install/Upgrade dependencies
#        run: |
#          python -m pip install --upgrade pip
#          python -m pip install -r ...txt

      - name: Run tests with pytest
        run: |
          python -m unittest discover -s tests/unit
          python -m unittest discover -s tests/integration
